fclose('all');
close all
clear
clc


timestamp = datestr(now,'yyyy-mm-dd_HHMM');
projectDir = '\\ROOT\projects\NIH-Light-Mask\Auckland';
saveDir = fullfile(projectDir,'cropped_data');
saveName  = [timestamp,'.mat'];
savePath  = fullfile(saveDir,saveName);

[objArray,dataPath] = loadData;

c = {...
'Pt01'	'placebo (red)'; ...
'Pt02'	'placebo (red)'; ...
'Pt03'	'active (blue)'; ...
'Pt04'	'placebo (red)'; ...
'Pt05'	'active (blue)'; ...
'Pt06'	'placebo (red)'; ...
'Pt07'	'active (blue)'; ...
'Pt08'	'active (blue)'; ...
'Pt09'	'placebo (red)'; ...
'Pt10'	'placebo (red)'; ...
'Pt11'	'placebo (red)'; ...
'Pt12'	'placebo (red)'; ...
'Pt13'	'active (blue)'; ...
'Pt15'	'active (blue)'; ...
'Pt16'	'placebo (red)'; ...
'Pt17'	'active (blue)'; ...
'Pt18'	'active (blue)'; ...
'Pt19'	'active (blue)'; ...
'Pt20'	'placebo (red)'; ...
'Pt21'	'active (blue)'; ...
'Pt22'	'placebo (red)'; ...
'Pt23'	'active (blue)'; ...
'Pt24'	'active (blue)'; ...
'Pt25'	'placebo (red)'; ...
'Pt26'	'placebo (red)'; ...
'Pt27'	'placebo (red)'; ...
'Pt28'	'active (blue)'; ...
'Pt30'	'placebo (red)'; ...
'Pt31'	'placebo (red)'; ...
'Pt32'	'active (blue)'; ...
};
t = cell2table(c,'VariableNames',{'ID','Condition'});

nObj = numel(objArray);
for iObj = 1:nObj
    idx = strcmp(objArray(iObj).ID,t.ID);
    thisCondition = t.Condition{idx};
    
    objArray(iObj).Session.Condition = thisCondition;
end

save(savePath,'objArray')